# Automatically review and merge PRs that resolve dependabot vulnerability alerts with minor or patch semver bumps.
#
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#approve-a-pull-request
# https://github.com/dependabot/fetch-metadata
name: Dependabot Checks
on: pull_request_target

permissions:
  contents: write
  pull-requests: write
  security-events: read

jobs:
  dependabot-approve-and-merge-alert-fixes:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v1.3.5
      with:
        alert-lookup: true
        github-token: "${{ secrets.PAT_GITHUB_TOKEN_ALERT_LOOKUP }}" # PAT token with only security_events scope
    - name: Approve and enable auto-merge for Dependabot alert PRs
      if: ${{contains(steps.metadata.outputs.alert-state, 'OPEN') && steps.metadata.outputs.update-type != 'version-update:semver-major'}}
      run: |
        set -eu
        gh pr edit --add-label "security" "$PR_URL"
        gh pr review --approve "$PR_URL"
        gh pr merge --auto --squash "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
